#!/bin/bash

# Loop through the subfolders to pull all together one by one.

path=$1
echo "Looping $path"
scriptdir=`dirname "$BASH_SOURCE"`

find "$path" -mindepth 1 -maxdepth 1 -type d | while read dir; do
  echo "git-subtree-pull $dir"
  bash $scriptdir/git-subtree-pull $dir
done
